### ISSUE TITLE
no time in userdefaults, no crashreports

### ISSUE THREAD

**Issue by yene** [tylerhall/OpenFeedback#2]
lastCrashCheckTime returns nil and this gets passed down to 
- (BOOL)file:(NSString *)filename isNewerThan:(NSDate *)time
  a possible dirty fix would be if (!time) return YES;
  cheers

**Comment by tylerhall** [comment]
Thanks for that. I've committed your fix.

http://github.com/tylerhall/OpenFeedback/commit/4222d125c9e48bb410d13ebfe492610ba5cfa94f
